version: '3'

services:
  app_fastapi:
    build:
      context: ./meteo_telegram
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
     - .:/app
    depends_on:
      - mongo
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - MONGO_URL=mongodb://mongo:27017/
    networks:
      - mynetwork
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level info

  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data:
